image: debian:latest

before_script:
  - apt update -y
  - apt install python
  - pip install termux-create-package

build:
  stage: build
  script:
    - chmod +x wanda.sh
    - chmod +x canvas.sh
    - termux-create-package manifest.json
  artifacts:
    paths:
      - wanda*.deb