image: python:latest

before_script:
  - pip install termux-create-package
  - v=0.31

build:
  stage: build
  script:
    - chmod +x wanda.sh
    - chmod +x canvas.sh
    - termux-create-package manifest.json
    - apt install ./*.deb
  artifacts:
    paths:
      - /*.deb