image: debian:latest

before_script:
  - apt-get install -y python3 python3-pip dh-make build-essential autoconf autotools-dev
  - apt-get update -y && apt-get upgrade -y && apt-get autoremove && apt-get autoclean
  - pip install termux-create-package

build:
  stage: build
  script:
    - chmod +x wanda.sh
    - chmod +x canvas.sh
    - termux-create-package manifest.json
    - tar cvfz wanda.tar.gz wanda*.deb
  artifacts:
    paths:
      - wanda*.deb
