image: python:latest

before_script:
  - pip install termux-create-package
  - v=0.32

build:
  stage: build
  script:
    - chmod +x wanda.sh
    - chmod +x canvas.sh
    - termux-create-package manifest.json
    - apt install ./wanda_$v_all.deb
  artifacts:
    paths:
      - wanda_$v_all.deb