image: debian:latest

before_script:
  - apt-get update -y && apt-get upgrade -y && apt-get autoremove && apt-get autoclean
  - apt install python3 -y
  - apt install python3-pip
  - pip install termux-create-package

build:
  stage: build
  script:
    - chmod +x wanda.sh
    - chmod +x canvas.sh
    - termux-create-package manifest.json
  artifacts:
    paths:
      - wanda*.deb