image: python:latest

before_script:
  - pip install termux-create-package


after_script:
  - echo "done"

build1:
  stage: build
  script:
    - termux-create-package manifest.json
    - apt install ./*.deb

test1:
  stage: test
  script:
    - wanda -h


deploy1:
  stage: deploy
  script:
    - echo $ls | grep .deb
