before_script:
  - apt install python
  - pip install termux-create-package


after_script:
  - echo "After script section"
  - echo "For example you might do some cleanup here"

build1:
  stage: build
  script:
    - termux-create-package manifest.json

test1:
  stage: test
  script:
    - wanda -h


deploy1:
  stage: deploy
  script:
    - echo $ls | grep .deb
