before_script:
  - apt install jq curl file libxml2-utils imagemagick

after_script:
  - echo "done"

build1:
  stage: build
  script:
    - echo "nothing to build"

test1:
  stage: test
  script:
    - sh wanda.sh -s wa -t mountains
    - sh wanda.sh -s ea
    - sh wanda.sh -s un -t eiffel tower


deploy1:
  stage: deploy
  script:
    - echo $ls | grep .deb
