#!/data/data/com.termux/files/usr/bin/bash
# please refer https://wallhaven.cc/help/api#search
apikey=
q=
categories=
purity=
sorting=random
order=
topRange=
atleast=
resolutions=
ratios=9x16,10x16,9x18
colors=
page=
seed=
