#!/data/data/com.termux/files/usr/bin/bash
# size for generating images (autopopulated, no need to change)
size=${width}x$height

# pattern number or code
# 1|solid
# 2|linear
# 3|radial
# 4|twisted
# 5|bilinear
# 6|plasma
# 7|blurred
# 8|gradient1
# 9|gradient2
# 10|plasma1
# 11|plasma2
# 12|gradient3
pattern=12

# max amount for blur effect
blur=60

# max amount for paint effect
paint=30
